import type { Metadata } from 'next';
import './globals.css';
import NextUiProvider from 'src/components/provider/NextUiProvider';
import CookieProvider from 'src/components/provider/CookieProvider';
import { inter } from 'src/fonts/fonts';
import TokenProvider from 'src/components/provider/TokenProvider';
import Header from 'src/components/Header/Header';
import StyledComponentsRegistry from 'src/lib/styled/registry';

export const metadata: Metadata = {
  title: 'Aritq',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <CookieProvider>
          <NextUiProvider>
            <TokenProvider>
              <StyledComponentsRegistry>
                <Header />
                {children}
              </StyledComponentsRegistry>
            </TokenProvider>
          </NextUiProvider>
        </CookieProvider>
      </body>
    </html>
  );
}
